extra-deps: [error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0, serialport-0.4.7,
  hspec-jenkins-0.1.1, hspec-2.2.4, hspec-core-2.2.4, hspec-discover-2.2.4, hspec-expectations-0.7.2,
  HUnit-1.3.1.2, containers-0.5.8.2]
ghc-options: {'*': -DFastCompilation -fenable-rewrite-rules -threaded -funbox-strict-fields
    -O0 -fconstraint-solver-iterations=100}
packages:
- {location: .}
- {location: ../core}
- extra-dep: true
  location: {commit: 51b24c9131c9385b2d8dfb232736ee830c4e09e5, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: fb625bbbb3672a5d2b2cef2dabde6d77f7625e7a, git: 'https://github.com/luna/data-pool.git'}
- extra-dep: true
  location: {commit: 54889cc56f3936281991df735e6918bb383d487e, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: 40517c0e2c0442dd41178a4f5783af917926574d, git: 'https://github.com/luna/data-base.git'}
- extra-dep: true
  location: {commit: 8ef98db28daa121b19ee4519f322ff1964469a8b, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: af39551ac65e2a625c39db55e34a285557476231, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 02afc8d3e8a2b90ea86784f3be33ec490a6398fd, git: 'https://github.com/luna/data-result.git'}
- extra-dep: true
  location: {commit: f76c292a6dc584beb9c55979257e8554dd9f31d6, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 89c5bdeca260dabf2e85e88e5a0bd1731dbd989a, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: e0b973e3371f5dde44eb58efa215d5f87d5fcfb9, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: b7b677616635261279c5748a2dcf0e711d181293, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: c3b75025446527d6ebf46b99fd21eadf75f06296, git: 'https://github.com/luna/poly-control.git'}
- extra-dep: true
  location: {commit: 81628a4f84c364d0b6cc5ab5bd75674f09520fa2, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: d5d82cab87037f34e0eb887b14d76ce92fe6105e, git: 'https://github.com/luna/type-cache.git'}
- extra-dep: true
  location: {commit: fec28ff165cc912265c3f63a90978f9acb63d55a, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: 8ef98db28daa121b19ee4519f322ff1964469a8b, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 95802e7a007733ff6555b802d573a65b9946eb80, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: cfed176570948e2ec60719131b86bf573c67ff44, git: 'https://github.com/luna/data-shell.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
- extra-dep: true
  location: {commit: 9dc37d5da8dd436aab39e74b33e624966cba3146, git: 'https://github.com/luna/monoid'}
resolver: lts-8.2
